const ROOT = 'postsList';

export const FETCH_POSTS_REQUEST = `${ROOT}/FETCH_POSTS_REQUEST`;
export const FETCH_POSTS_FAILURE = `${ROOT}/FETCH_POSTS_FAILURE`;
export const FETCH_POSTS_SUCCESS = `${ROOT}/FETCH_POSTS_SUCCESS`;